version: '3.8'
services:
  blog:
    image: ghost
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./assets:/var/lib/ghost/content/themes/attila/assets
      - ./partials:/var/lib/ghost/content/themes/attila/partials
      - ./author.hbs:/var/lib/ghost/content/themes/attila/author.hbs
      - ./default.hbs:/var/lib/ghost/content/themes/attila/default.hbs
      - ./error-404.hbs:/var/lib/ghost/content/themes/attila/error-404.hbs
      - ./error.hbs:/var/lib/ghost/content/themes/attila/error.hbs
      - ./gulpfile.js:/var/lib/ghost/content/themes/attila/gulpfile.js
      - ./index.hbs:/var/lib/ghost/content/themes/attila/index.hbs
      - ./package-lock.json:/var/lib/ghost/content/themes/attila/package-lock.json
      - ./package.json:/var/lib/ghost/content/themes/attila/package.json
      - ./page.hbs:/var/lib/ghost/content/themes/attila/page.hbs
      - ./post.hbs:/var/lib/ghost/content/themes/attila/post.hbs
      - ./query.hbs:/var/lib/ghost/content/themes/attila/query.hbs
      - ./tag.hbs:/var/lib/ghost/content/themes/attila/tag.hbs
      - ./readme.md:/var/lib/ghost/content/themes/attila/readme.md
    environment:
      url: http://localhost:2368
      NODE_ENV: development
      database__client: mysql
      database__connection__host: 192.168.0.175
      database__connection__port: 3308
      database__connection__user: root
      database__connection__password: X685p&0#QSzK5tUT
      database__connection__database: ghost_dev
      mail__transport: "SMTP"
      mail__options__host: "email-smtp.ap-southeast-1.amazonaws.com"
      mail__options__port: "465"
      mail__options__service: "SES"
      mail__options__auth__user: "AKIARPEPNA2Q6B2PM4GK"
      mail__options__auth__pass: "BFHf6NjMDa2vM6ATHWU/lFxf9h/WJtz8qjwLMfe5RX9L"
